name: release

#on:
#  push:
#    tags:
#    - 'v*'
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install target
      run: rustup target add x86_64-unknown-linux-gnu
    - name: Build
      run: cargo build --release --target=x86_64-unknown-linux-gnu
    - name: Upload binary
      uses: actions/upload-artifact@v3
      with:
        name: Linux-binary
        path: target/x86_64-unknown-linux-gnu/release/bar-rs

        
  windows:
    runs-on: windows-latest

    defaults:
      run:
        shell: bash
        
    steps:
    - uses: actions/checkout@v3
    - name: Install target
      run: rustup target add x86_64-pc-windows-gnu
    - name: Build
      run: cargo build --release --target=x86_64-pc-windows-gnu
    - name: Upload binary
      uses: actions/upload-artifact@v3
      with:
        name: Windows-binary
        path: target/x86_64-pc-windows-gnu/release/bar-rs
      

  release:
    runs-on: ubuntu-latest

    steps:
    - name: Download Linux
      uses: actions/download-artifact@v3
    - name: Create release
      uses: ncipollo/release-action@v1.13.0
      with:
        name: ${{  github.ref_name }}
        artifacts: "LICENSE-*,bar-rs*"
