name: release

on:
  push:
    tags:
    - 'v*'

env:
  CARGO_TERM_COLOR: always

jobs:
  linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install target
      run: rustup target add x86_64-unknown-linux-gnu
    - name: Build
      run: cargo build --release --target=x86_64-unknown-linux-gnu
    - name: Upload binary
      uses: actions/upload-artifact@v3
      with:
        name: bar-rs
        path: target/x86_64-unknown-linux-gnu/release/bar-rs

        
  windows:
    runs-on: windows-latest

    defaults:
      run:
        shell: bash
        
    steps:
    - uses: actions/checkout@v3
    - name: Install target
      run: rustup target add x86_64-pc-windows-gnu
    - name: Build
      run: cargo build --release --target=x86_64-pc-windows-gnu
    - name: Upload binary
      uses: actions/upload-artifact@v3
      with:
        name: bar-rs
        path: target/x86_64-pc-windows-gnu/release/bar-rs.exe
      

  release:
    needs: [windows, linux]
    runs-on: ubuntu-latest

    steps:
    - name: Download binaries
      uses: actions/download-artifact@v3
    - name: list files
      run: find
    - name: Create release
      uses: ncipollo/release-action@v1.13.0
      with:
        name: ${{  github.ref_name }}
        tag: ${{ github.ref_name }}
        artifacts: "bar-rs/*"
